# tui-ide: shared toolchain (macOS and Linuxbrew).
# Casks live in Brewfile.macos.
brew "git"
brew "gh"
brew "ansible"
brew "neovim"
brew "mosh"
brew "herdr"
brew "opencode"
brew "ripgrep"
brew "stow"
brew "jq"
brew "lazygit"
tap "cavanaug/tap-extras"
brew "cavanaug/tap-extras/mermaid-ascii"
brew "hashicorp/tap/terraform"
